<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [ ]:
indexing= i wan this cake
slicing= i wan this this this this this cake

In [1]:
import numpy as np

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # slicing works with both lists and arrays


In [3]:
py_list[0]

'a1'

In [4]:
py_list[-1]

'j10'

In [5]:
py_list[0:3]     #slicing specifies the start and end of the slice u wan
                    #[x:Y]= slice is 0 inde X <= slice <index Y
                    #number of variables taken out= y-1

['a1', 'b2', 'c3']

In [7]:
x=py_list

In [8]:
x[1:6]

['b2', 'c3', 'd4', 'e5', 'f6']

In [9]:
x[1:6:2]      #index 1 to 6 with steps of 2

['b2', 'd4', 'f6']

In [10]:
x[5:]      #all the way to the end

['f6', 'g7', 'h8', 'i9', 'j10']

In [11]:
x[5:]       #from index 5 to the end

['f6', 'g7', 'h8', 'i9', 'j10']

In [12]:
x[:5]      #index 0 to 5

['a1', 'b2', 'c3', 'd4', 'e5']

In [13]:
x[5:2:-1]    #index 5 to 3 but in reverse. the -1 is to indicate the reverse direction
            #cuz the slicing cannot go backwards on its own

['f6', 'e5', 'd4']

In [14]:
x[::-1] #reverse the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [20]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask= np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
np_array[my_mask]   #the mask had a condition of >3 is true. puting the mask in array
                    #shows the result only more than 3

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[np_array > 3]


array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
np_array[~(np_array > 3)]                 # '~' means 'NOT' so NOT greater than 3

array([1, 2, 3])

In [22]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [23]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [24]:
py_list_2d[3]

[4, 'D']

In [25]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [26]:
py_list_2d[3][0]        #index 3 first element

4

In [27]:
np_array_2d[3, 0]     #numpy works liike slicing with higher dimension lists


'4'

In [28]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [30]:
py_list_2d[:3][0] #pick the first[ ] then take index 0 of the :3 list

[1, 'A']

In [29]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [32]:
np_array_2d[:3, 0] #0 to 2 index and the 0 index of each thing

array(['1', '2', '3'], dtype='<U11')

In [33]:
np_array_2d[3:6, 0] #3 to 6 and choose the 0 

array(['4', '5', '6'], dtype='<U11')

In [34]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

NumPy arrays are fantastic for fast math operations, provided you do not change their size1. 

In [35]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [36]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [37]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [38]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [39]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [40]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x


[1, 2, 3, 4, 5, 6]

In [42]:
x=[1, 2, 3]
x.append([4, 5, 6]) #j adds another list into the existing list.
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [44]:
a=(1, 2, 3)     # Define tuple. tuple cannot be modified-all the -1 skip 2 slicing will not work


In [45]:
print(a[0])    # Access data

1


In [47]:
# The following will NOT work. it is written in stone. but you can convert turple, lists and arrays interchangably
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [48]:
x=[1, 2, 3]
y=x           # DON'T do this! dont use the copy function for lists
z=x           # DON'T do this!

In [49]:
x=[1, 2, 3] # the correct way to copy a list: creating a separate independent list
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes