<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

there are many ways to store data. how you organise your data will influence your way of thinking

# What to expect in this chapter

In [7]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**Python Lists**

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy**

In [ ]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionary**

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

start counting index from 0 left to right

## 1.2 Accessing data from a list (or array)

In [13]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
py_real_names[0]
print(py_real_names[0],' is' ,py_super_names[0])

i=2
print(py_real_names[i],' is' ,py_super_names[i])

Natasha Romanoff  is Black Widow
Stephen Strange  is Doctor Strange


In [ ]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

In [14]:
py_super_names[-1]   # Reverse indexing count from the back

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [15]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

superhero_info["Natasha Romanoff"]

'Black Widow'

cannot use the value to get the key, but the key can be used to access the value

In [18]:
superhero_info.keys()          #can get all the keys. similarly can get all the values too 
                                #if i swap keys with .value()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

## 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [
    ['Natasha Romanoff', 'Black Widow'],
    ['Tony Stark', 'Iron Man'],
    ['Stephen Strange', 'Doctor Strange']
]

the first item of the sublist is this this and the second item is that that. its a list within a list

# 2 Lists vs. Arrays

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [22]:
np_array_2d         #can only hold a single type of variable. either str or int or wtv
                    # it will convert everything into the type that is most common alr

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C'],
       ['4', 'D'],
       ['5', 'E'],
       ['6', 'F'],
       ['7', 'G'],
       ['8', 'H'],
       ['9', 'I'],
       ['10', 'J']], dtype='<U11')

In [24]:
py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

## 2.1 Size

In [25]:
len(py_list_2d)

10

In [26]:
len(np_array_2d)

10

In [27]:
np_array_2d.shape            #can get the shape of the list. 10x2 columns. additional way of getting the size


(10, 2)

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

## 2.4 Adding another list

In [33]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2             #things will be pasted tgt


[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [32]:
np_array_1 + np_array_2           #individual matching index will be added together


array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [35]:
py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [36]:
np_array*2      #as if its a mathamatical operation

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [38]:
py_list**2                      # Won't work!  bc cant multiply a list by itself

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [39]:
np_array**2

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [41]:
py_list == 3     # Works, but what IS the question? ask this qn need to use arrays

False

In [42]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [45]:
np_array == 3  #it asks the same question for each individual index

array([False, False,  True, False, False])

In [44]:
np_array > 3  

array([False, False, False,  True,  True])

In [46]:
sum(np_array > 3 )      #dosent work if theres a letter within the list

2

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [ ]:
sum(py_list)     # sum() is a base Python function

max(py_list)     # max() is a base Python function

min(py_list)     # min() is a base Python function

py_list.sum()   # Won't work!

In [48]:
np_array.sum()        #optimised and build within array .sum cannot be used on a list

np_array.max()         #list, convery to array to do math then go back to lists    

np_array.min()

np_array.mean()

np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes